server:
  servlet:
    context-path: /usuario-post/api

spring:    
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://wakandadev:ZwtTqntmqxPS5kyX@wakandadev.cjsar7m.mongodb.net/usuario-postDB?retryWrites=true&w=majority}
      auto-index-creation: true
      
springdoc:
  swagger-ui:
    path: /public/swagger

user-post:    
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}